import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import'./style.css';
const API='http://localhost:8080/api';
async function api(path,options={}){const r=await fetch(API+path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const body=await r.json().catch(()=>null);if(!r.ok){const e=new Error(body?.detail||'Request failed');e.body=body;throw e}return body}
const statuses=['OPEN','IN_PROGRESS','RESOLVED','CLOSED','CANCELLED'];
function App(){const[tickets,setTickets]=useState([]),[selected,setSelected]=useState(null),[q,setQ]=useState(''),[status,setStatus]=useState(''),[error,setError]=useState(''),[showCreate,setShowCreate]=useState(false);
 const load=async()=>{try{setError('');setTickets(await api(`/tickets?q=${encodeURIComponent(q)}${status?'&status='+status:''}`))}catch(e){setError(e.message)}};useEffect(()=>{load()},[q,status]);
 return <div className="app"><header><h1>Support Tickets</h1><button onClick={()=>setShowCreate(true)}>+ New ticket</button></header><div className="toolbar"><input placeholder="Search title or description" value={q} onChange={e=>setQ(e.target.value)}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{statuses.map(s=><option key={s}>{s}</option>)}</select></div>{error&&<div className="error">{error}</div>}<main><section className="list">{tickets.map(t=><button className={'ticket '+(selected?.id===t.id?'active':'')} key={t.id} onClick={()=>setSelected(t)}><b>{t.title}</b><span>{t.status} · {t.priority}</span></button>)}{!tickets.length&&<p>No tickets found.</p>}</section>{selected&&<Detail ticket={selected} refresh={async()=>{const fresh=await api('/tickets/'+selected.id);setSelected(fresh);load()}}/>}</main>{showCreate&&<Create close={()=>setShowCreate(false)} done={t=>{setShowCreate(false);setSelected(t);load()}}/>}</div>}
function Detail({ticket,refresh}){const[err,setErr]=useState(''),[comment,setComment]=useState(''),[edit,setEdit]=useState({title:ticket.title,description:ticket.description,priority:ticket.priority,assignee:ticket.assignee||''});const next={OPEN:['IN_PROGRESS','CANCELLED'],IN_PROGRESS:['RESOLVED','CANCELLED'],RESOLVED:['CLOSED'],CLOSED:[],CANCELLED:[]}[ticket.status]||[];useEffect(()=>setEdit({title:ticket.title,description:ticket.description,priority:ticket.priority,assignee:ticket.assignee||''}),[ticket]);async function transition(s){try{setErr('');await api(`/tickets/${ticket.id}/transitions`,{method:'POST',body:JSON.stringify({status:s})});refresh()}catch(e){setErr(e.message)}}async function save(){try{setErr('');await api(`/tickets/${ticket.id}`,{method:'PATCH',body:JSON.stringify(edit)});refresh()}catch(e){setErr(e.message)}}async function add(){try{await api(`/tickets/${ticket.id}/comments`,{method:'POST',body:JSON.stringify({author:'Support Agent',body:comment})});setComment('');refresh()}catch(e){setErr(e.message)}}return <section className="detail"><h2>Ticket #{ticket.id}</h2>{err&&<div className="error">{err}</div>}<input maxLength="200" value={edit.title} onChange={e=>setEdit({...edit,title:e.target.value})}/><textarea maxLength="5000" value={edit.description} onChange={e=>setEdit({...edit,description:e.target.value})}/><div className="editrow"><select value={edit.priority} onChange={e=>setEdit({...edit,priority:e.target.value})}>{['LOW','MEDIUM','HIGH','URGENT'].map(x=><option key={x}>{x}</option>)}</select><input maxLength="120" placeholder="Assignee" value={edit.assignee} onChange={e=>setEdit({...edit,assignee:e.target.value})}/><button onClick={save}>Save changes</button></div><h3>Status: {ticket.status}</h3><div className="actions">{next.map(s=><button key={s} onClick={()=>transition(s)}>Move to {s}</button>)}</div><h3>Comments</h3>{ticket.comments.map(c=><div className="comment" key={c.id}><b>{c.author}</b><p>{c.body}</p></div>)}<textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="Add a comment"/><button disabled={!comment.trim()} onClick={add}>Add comment</button></section>}
function Create({close,done}){const[f,setF]=useState({title:'',description:'',priority:'MEDIUM',assignee:''}),[err,setErr]=useState('');async function submit(e){e.preventDefault();try{setErr('');done(await api('/tickets',{method:'POST',body:JSON.stringify(f)}))}catch(e){setErr(e.message)}}return <div className="modal"><form onSubmit={submit}><h2>Create ticket</h2>{err&&<div className="error">{err}</div>}<input required maxLength="200" placeholder="Title" value={f.title} onChange={e=>setF({...f,title:e.target.value})}/><textarea required maxLength="5000" placeholder="Description" value={f.description} onChange={e=>setF({...f,description:e.target.value})}/><select value={f.priority} onChange={e=>setF({...f,priority:e.target.value})}>{['LOW','MEDIUM','HIGH','URGENT'].map(x=><option key={x}>{x}</option>)}</select><input maxLength="120" placeholder="Assignee" value={f.assignee} onChange={e=>setF({...f,assignee:e.target.value})}/><div><button type="submit">Create</button><button type="button" onClick={close}>Cancel</button></div></form></div>}
createRoot(document.getElementById('root')).render(<App/>);
