spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/support_ticket
    username: support
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
